### ISSUE TITLE
请求解答疑问

### ISSUE THREAD

**Issue by Strangerty** [sometiny/overfrp#1]
大佬，server和client部署在同一个机器上吗？我尝试部署在通一台机器上内网无法访问。

**Comment by sometiny** [comment]
项目中的代码为测试，部署在同一台服务器的。
实际应用你应该把server部署在服务器上，client部署在被穿透的设备上。
你可以直接跑README和README-2的用例，测试都是通过的。

**Comment by Strangerty** [comment]
我试了测试的用例访问baidu无法访问，服务是正常的
![1](https://github.com/user-attachments/assets/8d5dd4ba-8102-41eb-b895-2f18a7968178)

**Comment by sometiny** [comment]
```bash
wget http://127.0.0.1:7660
```
应该会正常输出baidu的内容。

**Comment by Strangerty** [comment]
部署的机器上是获取到了baidu的内容，但是内网的其他其他服务器无法直接访问吗？

**Comment by sometiny** [comment]
那你tunnel不应该监听127.0.0.1:7660，你应该监听一个内网其他机器能访问到的ip，例如：192.168.1.12:7660。
127.0.0.1是回环地址，只能本机访问。

**Comment by Strangerty** [comment]
可以了，感谢大佬指点。
